/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DiyBottom: typeof import('./src/components/diy-bottom/diy-bottom.vue')['default']
    DiyCollapse: typeof import('./src/components/diy-collapse/diy-collapse.vue')['default']
    DiyEmpty: typeof import('./src/components/diy-empty/diy-empty.vue')['default']
    DiyForm: typeof import('./src/components/diy-form/diy-form.vue')['default']
    DiyImage: typeof import('./src/components/diy-image/diy-image.vue')['default']
    DiyImage2: typeof import('./src/components/diy-image2/diy-image2.vue')['default']
    DiyMsgess: typeof import('./src/components/diy-msgess/diy-msgess.vue')['default']
    DiyNone: typeof import('./src/components/diy-none/diy-none.vue')['default']
    DiyPlayer: typeof import('./src/components/diy-player/diy-player.vue')['default']
    DiySep: typeof import('./src/components/diy-sep/diy-sep.vue')['default']
    DiySvga: typeof import('./src/components/diy-svga/diy-svga.vue')['default']
    DiySwiper: typeof import('./src/components/diy-swiper/diy-swiper.vue')['default']
    DiyTest: typeof import('./src/components/diy-test/diy-test.vue')['default']
    DiyTitle: typeof import('./src/components/diy-title/diy-title.vue')['default']
    DiyTop: typeof import('./src/components/diy-top/diy-top.vue')['default']
    DiyZixunBestComment: typeof import('./src/components/diy-zixun-item/diy-zixun-best-comment.vue')['default']
    DiyZixunItem: typeof import('./src/components/diy-zixun-item/diy-zixun-item.vue')['default']
    DiyZixunItemBottom: typeof import('./src/components/diy-zixun-item/diy-zixun-item-bottom.vue')['default']
    DiyZixunItemMany: typeof import('./src/components/diy-zixun-item/diy-zixun-item-many.vue')['default']
    DiyZixunItemRight: typeof import('./src/components/diy-zixun-item/diy-zixun-item-right.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanDatePicker: typeof import('vant/es')['DatePicker']
  }
}
