export interface TabListType {
  index: number
  name: string
  id: string
}
// Generated by https://quicktype.io

export interface ScheduleType {
  anchorReserveList: AnchorReserveListType[]
  eventInfo:         EventInfoType
}

export interface AnchorReserveListType {
  uid:                number
  username:           string
  avatar:             string
  avatarThumbnail:    string
  isLive:             number
  eventId:            number
  introduction:       string
  pullm3u8:           string
  title:              string
  webPagePath:        string
  h5PagePath?:        string | number
  internetFlag:       number
  isKing?:            string | number
  pull:               string
  attentionTotal:     number
  fictitiousUrl?:     string | number
  anchorLabel:        string
  ranking:            number
  coverImage:         string
  liveInputType:      number
  membershipLabel?:   string | number
  signature?:         string | number
  userLevel?:         string | number
  vipLevelId?:        string | number
  vipLevelName?:      string | number
  leagueLabel?:       string | number
  fansTotal?:         string | number
  attentionMark?:     string | number
  winLabelList?:      string | number
  isPufferFish?:      string | number
  zbtype?:            string | number
  age?:               string | number
  height?:            string | number
  weight?:            string | number
  threeCircumference?:string | number
  hobby?:             string | number
  personalSignature?: string | number
  isAnchor?:          string | number
  describe?:          string | number
  endTime?:           string | number
}

export interface EventInfoType {
  dataId:                     number
  eventId:                    number
  homeTeam:                   string
  homeTeamLogoUrl:            string
  awayTeam:                   string
  awayTeamLogoUrl:            string
  startTime:                  number
  endTime:                    number
  reserveMark:                number
  eventType:                  string
  eventName:                  string
  eventLevel:                 number
  anchorIds:                  string
  sort?:                      string | number
  leagueMatch?:               string | number
  beginTime?:                 string | number
  matchStartStatus:           number
  firstPlanId:                number
  planCount:                  number
  planListH5Url:              string
  planTitle:                  string
  planDetailsForContestPcUrl?:string | number
  planDetailsForContestH5Url?:string | number
  homeTeamScore:              number
  awayTeamScore:              number
  status?:                    string | number
}

export interface ScheduleTypesType {
  eventType: number
  name     : string
  id       : string
}
export interface ScheduleDatesType {
  eventDate: string
  name     : string
  timestamp: number
  dateTime:  string
  id:        string
  index:     number
}

export interface AnchorType {
  avatar       : string
  city         : string
  isKing       : boolean
  islive       : string
  label_icon   : string
  label_name   : string
  labelid      : string
  pageview     : string
  pull         : string
  pullm3u8     : string
  stream       : string
  thumb        : string
  title        : string
  type         : string
  uid          : string
  user_nicename: string
  zbtype       : string
  zbtype_detail: string
}

// 清流列表数据类型
export interface StreamSubItemType {
  class1: number
  cnName: string
  description: string
  event_id: number
  keywords: string
  title: string
}
export interface StreamCateItemType {
  description: string
  id: number
  keywords: string
  name: string
  num: number
  sub_list?: StreamSubItemType[]
  title: string
  url: string
}
export interface StreamDataItemOfInfoType {
  fName:  string
  dName:  string
  time:   number
  daySeq: number
}

export interface HbInfoType {
  hb_name:   string
  room_link: string
}

export interface LqEventInfoType {
  new_hb: NewHbType
}

export interface NewHbType {
  username:  string
  room_link: string
}

export interface PlayCodeType {
  src:         number
  name:        string
  cat:         number
  lcOrd:       number
  gtvId:       number
  id:          number
  preview_url: string
  pCode:       PCodeType
  status:      number
  pic:         string
}

export interface PCodeType {
  v:  number
  pl: number
  k:  string
  ip: string
  iv: string
  ua: string
  sn: string
  sa: string
  si: string
}

export interface StreamDataItemOfDataType {
  homeLogo:           string
  awayLogo:           string
  leagueEnName:       string
  eventName:          string
  startTime:          string
  endTime:            number
  id:                 number
  hots:               number
  isHot:              null
  event_id:           number
  mstartTime:         number
  homeTeamId:         number
  awayTeamId:         number
  homeName:           string
  awayName:           string
  homeNEName:         string
  awayNEName:         string
  class1Name:         string
  class1:             number
  gqId:               number
  lsId:               number
  qtlsId:             number
  LqEventInfo:        LqEventInfoType
  playCode:           PlayCodeType[]
  matchScore:         string
  remainTime:         string
  matchNode:          string
  home_score:         number
  away_score:         number
  pastStatus:         number
  pastTime:           string
  win:                number
  anchors:            any[]
  url:                string
  home_url:           string
  url_type:           number
  away_url:           string
  appointment_status: number
  hb_info:            HbInfoType
}
export interface StreamDataItemType {
  data: StreamDataItemOfDataType[] | []
  info: StreamDataItemOfInfoType
}
export interface StreamDataType {
  cate_list: StreamCateItemType[]
  cate_total_num: number
  data: any
  hot_num: string
  list: StreamDataItemType[]
  message: string
  name: string
  status: number
  total: number
  url: string
  url_type: number
}
// Generated by https://quicktype.io

export interface InitUserInfoType {
  uid:                            number
  username:                       string
  level:                          string
  signAture:                      null
  isAnchor:                       number
  diamondsTotal:                  null
  redDiamond:                     null
  fansTotal:                      number
  attentionTotal:                 null
  avatar:                         string
  avatarThumbnail:                string
  isLive:                         number
  liveInputType:                  number
  subscriptionMark:               number
  pullm3u8:                       string
  title:                          string
  changedUserName:                null
  token:                          null
  userStatus:                     null
  remark:                         null
  signature:                      string
  coin:                           null
  consumption:                    null
  titleName:                      null
  titleResourceUrl:               null
  titleResourceThumbUrl:          null
  medalCount:                     null
  medalLevel:                     null
  medalResourceUrl:               null
  medalResourceThumbUrl:          null
  membershipLabel:                string
  leagueLabel:                    string
  specialSkill:                   null
  currentExperience:              null
  currentLevelExperience:         null
  nextExperience:                 null
  isKing:                         number
  isAttention:                    null
  fishBallLevel:                  null
  joinVip:                        number
  vipLevel:                       number
  vipLevelTitle:                  null
  fishBall:                       null
  vipLevelId:                     null
  vipLevelName:                   null
  nextFishBallExperience:         null
  currentFishBallExperience:      null
  currentFishBallLevelExperience: null
  joinIntimacyGroupFlag:          null
  rewardRatio:                    null
  winRatio:                       null
  talentDetails:                  null
  isPufferFish:                   null
  createTime:                     null
}

export interface UniImageType {
  src: string
  width?: string | number
  height?: string | number
  mode?: string
  display?: string
  defaultSrc?: string
  round?: string
}